Feat/#90 메인페이지 게시글 api 연동
ODOICHON/frontend pull request #103
Opened 2023-05-29 02:05 UTC by JunJongHun

## 📖 개요
- 게시글 데이터 가져오는 새로운 api 적용

## 💻 작업사항

- 메인 페이지 / 오도이촌 소개 페이지 게시글 정보 불러오기 api 적용
- 메인 페이지 / 오도이촌 소개 페이지 새로운 api 적용함에 따라 코드 수정

## 💡 작성한 이슈 외에 작업한 사항

- 새로운 api 응답값 Type 추가 => 게시글 type 관련

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2023-05-29 09:32 UTC, sangminlee98 approved these changes
API가 변경되면서 기존 작성된 코드를 변경된 API로 잘 적용해주시고 추가적으로 리팩토링 해주셨는데 너무 깔끔하고 가독성이 훨씬 좋아진 것 같아요!!
너무 고생하셨습니다 🙇‍♂️

2023-05-29 09:32 UTC, sangminlee98 commented on src/pages/Introduce/index.tsx
> +  );
prefetch까지 고려해주신거 너무 좋은 것 같아요!!
하지만 고려해봐야할 부분은 페이지네이션이 적용된 API가 아니다보니 **Total Page가 몇인지를 모르기 때문에** 마지막 페이지에서도 다음 페이지를 prefetch하는 것 같아요!
물론 해당 API 에서는 실제 page로 요청하는 것이 아닌 limit으로 요청하기 때문에 문제는 없지만 마지막 페이지에서는 불필요한 API 요청을 한번 더 한다는 단점이 있는 것 같습니다.
마지막 페이지인지 판단할 수 있다면 좋겠지만, 페이지네이션 API가 아니다보니 힘들 것 같아서.. 두 가지 방법을 고려해볼 수 있을 것 같아요!

1. 지금 방식처럼 prefetch를 사용하여 사용자가 로딩없이 데이터를 볼 수 있도록 한다. 그 대신 마지막 페이지에서는 불필요한 API 요청이 추가적으로 한번 더 일어난다.
2. prefetch를 포기하여 불필요한 API 요청을 하지 않는 대신 사용자가 로딩을 보아야 한다.

종훈님은 둘 중에 어떤게 더 낫다고 생각하시나요 ?!

2023-05-29 09:32 UTC, sangminlee98 commented on src/pages/Introduce/index.tsx
> +  };
새롭게 적용된 API를 활용하니 기존 state들과 slice하는 과정 없이 4 * nowPage를 통해 4개씩 잘라서 가져옴으로서 코드가 확 줄어든 것 같아요!! 너무 좋습니다 👍

2023-05-29 09:32 UTC, sangminlee98 commented on src/pages/Main/index.tsx
>        }),
category값을 동적으로 받으면서 불필요한 state를 없애고 introData 하나로 통일하여 관리하니까 코드도 간결해지고 가독성도 훨씬 좋아진 것 같아요!!
리팩토링 너무 잘해주신 것 같아요 ㅎㅎ 감사합니다 !! 👍

2023-05-29 10:01 UTC, sangminlee98 requested changes
Main 컴포넌트에 슬라이드뷰 클릭 이벤트 (네비게이트 경로)만 수정해주시면 될 것 같아요 ! 👍

2023-05-29 10:01 UTC, sangminlee98 commented on src/pages/Main/index.tsx
>                    onClick={() => navigate('/community')}
클릭했을 때 `/community`로 이동하게끔 하기 보다 클릭한 게시물 상세페이지로 이동하게 코드 수정하면 좋을 것 같아요 !

2023-05-29 17:23 UTC, JunJongHun commented on src/pages/Introduce/index.tsx
> +  );
이 부분에 대해서 고민을 혼자 많이 해봤습니다🥲 react-query 공식문서를 찾아보며 활용할 수 있는 옵션들은 뭐가 있을까.. 돌고 돌아 코드를 작성했습니다.

우선 제가 prefetch 해야겟다! 라고 선택한 이유는 다음과 같습니다.
- 기존에 작동하던 '더 많은 트렌드 보러가기' 버튼이 기존 페이지네이션 적용된 api를 사용할 때는 page를 비교해서 더 이상 요청을 안해도 되겠다 판단이 되면 버튼을 disable하는 방식으로 불필요한 api요청을 막는 방법이였습니다. 
- 새로운 api는 페이지네이션이 없기에 어떤 것으로 판단할지 애매했습니다! 기존과 똑같이 작동하게 만들기 위해서는 prefetch를 해서 현재값과 prefetch값의 개수를 비교해서 같다면 버튼을 disable 하는 방식을 선택했습니다😄

다른 방법으로는 버튼을 disable 할 방법이 딱히 떠오르지 않았습니다😂

상민님이 주신 의견에 개인적인 생각을 답변해보겠습니다.
- 상황에 따라 다르긴 할 것 같습니다. 연산이 복잡한 api 요청이라면 서버에 부하가 갈 수 있다고 생각을 해서 불필요한 api 요청을 줄여야 한다고 생각합니다. 반대로 연산이 간단한 api 요청이라면 사용자를 고려해서 prefetch 방식을 택하는게 어떤가 싶습니다🤓

현재 프로젝트에서는 불필요한 요청이 마지막에 한번 작동을 하지만 연산이 복잡한 api가 아니라고 생각하기 때문에 괜찮아 보입니다!

혹시 현재 api에서 불필요한 요청을 막으면서 버튼을 disable 할 수 있는 방법이 생각나신다면 조언 부탁드립니다!🙇‍♂️

2023-05-29 17:26 UTC, JunJongHun commented on src/pages/Introduce/index.tsx
> +  };
감사합니다🙇‍♂️

현 프로젝트에서 4개씩 보여주기로 얘기가 되어있기 때문에 4를 명시적으로 적었는데, 이를 `const LIMT_COUNT = 4` 이런식으로 상수로 관리할까 생각을 해보긴 했습니다. 이 파일에서 4를 중복해서 사용하고 있기도 하고 개수의 변동이 있을 때, 유지보수도 좋을 것 같긴 합니다. 

어떻게 생각하시나요?

2023-05-30 02:50 UTC, JunJongHun commented on src/pages/Main/index.tsx
>                    onClick={() => navigate('/community')}
리뷰 남겨주신대로 코드를 수정했습니다! 소개글을 누르면 해당 상세페이지로 이동 합니다!

이동은 잘 되지만 뒤로가기가 안되네요..😂 혹시 코드 보시고 확인 부탁 드려도 될까요? 이유를 모르겟습니다🥲

2023-05-30 06:01 UTC, sangminlee98 commented on src/pages/Introduce/index.tsx
> +  );
음.. prefetchTrendData를 useQuery로 요청하는 코드에서
prefetchTrendData와 TrendData의 길이가 같다면, fetch를 안하는 건 어떨까요??

```typescript
const { data: prefetchTrendData } = useQuery<BoardMainResponse>(
    [QueryKeys.INTRO_BOARD, 'TREND', page + 1],
    () => fetchTrendList(page + 1),
    {
      enabled: prefetchTrendData.length !== trendData.length
    }
  );
```

일단 지금 생각했을땐 `enabled` 옵션을 사용해서 가능할 것 같다고 생각했어요!
혹시 적용해보시겠어요 ??

2023-05-30 06:02 UTC, sangminlee98 commented on src/pages/Introduce/index.tsx
> +  };
매직넘버를 사용하기보다 종훈님 말씀처럼 상수화를 하는게 좋을 것 같아요!!
이 부분은 따로 constants에 빼지 않고 해당 파일 내에서 선언해도 괜찮을 것 같습니다 👍

2023-05-30 06:14 UTC, sangminlee98 commented on src/pages/Main/index.tsx
>                    onClick={() => navigate('/community')}
현재 navigate를 ```navigate(`/community/${data.prefixCategory}/${data.boardId}`)```로 하고 계십니다.
data.prefixCategory는 `ADVERTISEMENT`와 같은 대문자 값입니다. 따라서 해당 navigate를 실행하면 URL 경로는
`https://duaily.net/community/ADVERTISEMENT/42`형식으로 이동됩니다.

pages/Community/Detail에 아래와 같은 코드가 있습니다.
```typescript
if (
    boardData &&
    category !== getPrefixCategoryName(boardData.data.prefixCategory)
  ) {
    const prefixCategory = getPrefixCategoryName(
      boardData?.data.prefixCategory,
    );
    return <Navigate to={`/community/${prefixCategory}/${id}`} />;
  }
```
`https://duaily.net/community/ADVERTISEMENT/42`경로로 접근한다면 위 코드를 통해 `https://duaily.net/community/advertisement_board/42` 경로로 변환되어서 접근합니다.

결국 경로는 `/` -> `/community/ADVERTISEMENT/42` -> `/community/advertisement_board/42` 의 순서대로 이동합니다.

따라서 `/community/advertisement_board/42`경로에서 뒤로가기를 하면 `/community/ADVERTISEMENT/42`경로로 이동이 되는 것이고 **해당 경로에서 다시 리다이렉트가 되므로 뒤로가기가 동작되지 않는 것처럼 보이는 것입니다!**

2023-05-30 06:43 UTC, sangminlee98 commented on src/pages/Introduce/index.tsx
> +  );
위에 말씀드린 코드 제가 직접 해보니까 안되네요... 🥹
직접 queryClient에서 값을 가져와서 비교해보려고 하다가 생각해보니 결국 의미가 없어서..
종훈님 말씀대로 마지막에 데이터 요청을 한번 더 하는것이 가장 깔끔할 것 같아요!
복잡한 API 요청도 아니어서 괜찮을 것 같다고 생각합니다 :)

2023-05-30 06:46 UTC, JunJongHun commented on src/pages/Introduce/index.tsx
> +  );
저도 코드를 작성해보니 prefetchTrendData 값을 `enabled: prefetchTrendData.length !== trendData.length`에서 사용을 할 수가 없네요ㅜ 아마도 응답을 받기 전에 실행되는 로직이다보니 값을 조회하지 못하는 것 같습니다😂

아무래도 api 응답값에 다음 요청을 할지말지에 대한 비교할 데이터가 없기 때문에 불필요한 요청은 최소 한번 해야하는게 맞을 것 같아요😂

2023-05-30 06:48 UTC, JunJongHun commented on src/pages/Introduce/index.tsx
> +  };
**매직넘버**라는 말을 처음 들어봐서 검색을 해봤는데, '의미 있는 이름의 상수로 대체될 수 있는 숫자' 라고 하네요!
덕분에 개발 지식 하나 알아갑니다👍

2023-05-30 09:08 UTC, JunJongHun commented on src/pages/Main/index.tsx
>                    onClick={() => navigate('/community')}
깔끔한 설명 감사합니다 ㅎㅎ 알려주신대로 반영해서 코드 수정했고 제대로 작동합니다!

2023-05-30 16:17 UTC, sangminlee98 commented on src/pages/Introduce/index.tsx
> +  );
넵..! 좋아요! 나중에 더 좋은 방법이 있다면 리팩토링 적용합시다 🥹

2023-05-30 16:17 UTC, sangminlee98 commented on src/pages/Main/index.tsx
>                    onClick={() => navigate('/community')}
좋아요! 고생하셨습니다 :)

2023-05-30 16:18 UTC, sangminlee98 approved these changes
수정사항 전부 확인했습니다! 👍

2023-05-31 09:23 UTC, merged