Feat/#129 애니매이션 적용 안된 페이지 애니메이션 적용
ODOICHON/frontend pull request #130
Opened 2023-06-28 23:17 UTC by JunJongHun

## 💻 작업사항

- 페이지 이동 시, 애니메이션 적용

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2023-06-29 08:15 UTC, sangminlee98 requested changes

2023-06-29 08:15 UTC, sangminlee98 commented on src/pages/Community/Board/index.tsx
> +      <div className={styles.container}>
굳이 상위에 div태그를 만들지 않고 기존 container 태그에 motion.div를 적용해도 괜찮을 거 같아요!

2023-06-29 08:15 UTC, sangminlee98 commented on src/pages/Community/Detail/index.tsx
> +      <section className={styles.container}>
위와 같은 피드백입니다!

2023-06-29 08:15 UTC, sangminlee98 commented on src/pages/NotFound/index.tsx
> +        }
위와 같은 피드백입니다!

2023-06-29 08:15 UTC, sangminlee98 commented on src/pages/Trade/Board/index.tsx
> +        <div className={styles.title}>
위와 같은 피드백입니다!

2023-06-29 22:03 UTC, JunJongHun commented
@sangminlee98 

불필요한 div 제거 피드백 주신 내용 적용 했습니다😄

불필요한 태그들을 줄이는 습관을 가지는게 좋다고 들었는데, 코드를 작성할 때 불필요한 코드는 없는지 확인을 해봐야겠네요👍

2023-06-30 08:19 UTC, sangminlee98 approved these changes
고생하셨습니다 👍

2023-06-30 17:20 UTC, merged