Feat/#122 빈집거래 매물 상세 페이지 API 연동
ODOICHON/frontend pull request #147
Opened 2023-07-13 02:36 UTC by JunJongHun

## 📖 개요
- 빈집거래 상세 페이지 api 연동

## 💻 작업사항

- 빈집거래 관련 api 연결 완료

## 💡 작성한 이슈 외에 작업한 사항

- 신고 모달창 구현 및 api 연동
- 스크랩 낙관적 업데이트 적용
- develop 브랜치랑 merge 

## 🙏 요청사항

- 모바일 크기일 때, 게시글 제목 부분을 반응형 어떤식으로 해야할지 조언 부탁드립니다! 감이 잘 안와요..😭

- 스크랩 부분 낙관적 업데이트 적용했는데, 방식이 맞는지 확인 부탁드립니다.
 - 제가 생각한 낙관적 업데이트 방식 ( 현 프로젝트 react-query 사용 기준 )
  - 스크랩을 누르면 사용자 기대값으로 즉시 업데이트 한다. ( 클라이언트 캐시 상태 먼저 업데이트, 백엔드와 데이터 불일치 상태 )
  - 업데이트 하기 전, 캐시값을 가지고 있는다.
  -  api 요청 후 성공적이면 더이상 작업할 것은 없다 -> 낙관적 업데이트를 통해서 임의로 업데이트 했지만, 성공을 했다면 백엔드와 데이터 일치 할 것이기 때문
  - api 요청 후, 실패했다면 이전 캐시값으로 다시 복구 시킨다.
  
  - 신고하기 모달창을 띄우고 뒤에 배경을 옅은 회색으로 처리했습니다. 이때, 스크롤을 멈추게 할지 말지에 대한 여부와 만약 스크롤을 멈추는 쪽을 선택한다면 스크롤 숨김에 대해서 어떻게 해결할지에 대한 의견을 구해봅니다. 현재 저는 document를 직접 조작해서 body에 overflow:hidden을 넣는 방식 밖에 생각이 나지 않아서 그렇습니다! 

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2023-07-13 13:31 UTC, sangminlee98 requested changes
1. 모바일 크기일 때 게시글 제목은 지금처럼 둬도 괜찮지 않을까 싶어요..!
다만 오른쪽에 위치해 있는 신고하기와 스크랩 버튼이 모바일에서 너무 크게 보여서 영역을 침범하는 것 같습니다! 사이즈 적용해주면 괜찮을 것 같아요!

2. 낙관적 업데이트에 관한 피드백은 코드리뷰에 포함했습니다 🙂

3. 모달에 관련된 피드백도 코드리뷰에 포함했습니다 🙂

로그인하지 않은 유저는 스크랩과 신고하기 버튼이 보이지 않게 구현하신 부분이 디테일하게 신경쓰신것 같아서 좋아요 🙌
한 가지 궁금한 점이 있는데, 현재 연동한 API에서 썸네일 사진이 404로 불러와지지 않더라구요! 해당 부분은 서버쪽에서 원래 404인 이미지를 넣어서 그런걸까요?

2023-07-13 13:31 UTC, sangminlee98 commented on src/components/Trade/Report/ReportIcon/index.tsx
> +        }}
신고하기 아이콘 크기가 지정이 되지 않은 것 같아요!
피그마랑 맞춰서 크기를 rem으로 지정해주는 것이 좋을 것 같아요! (지금은 조금 커보이는 것 같아요..!)
모바일에서 봤을때 특히 사이즈가 너무 커서 제목 영역이랑 살짝 겹치는 것 같은데
모바일에서는 사이즈를 더 줄일 수 있도록 따로 반응형 처리를 해도 좋을 것 같습니다! 👍

2023-07-13 13:31 UTC, sangminlee98 commented on src/components/Trade/Report/ReportIcon/index.tsx
> +      />
해당 부분은 스크롤 고정 방식이 좋을 것 같아요!
`src/components/Terms` 파일을 확인해 보시면 약관 모달에도 해당 코드가 구현되어 있어 참고하시면 될 것 같습니다 :)

```tsx
const onToggleClick = () => {
    const bodyEl = document.querySelector('body');
    bodyEl?.classList.remove('over_hidden');
    setToggle(false);
  };
```

2023-07-13 13:31 UTC, sangminlee98 commented on src/components/Trade/Report/ReportIcon/index.tsx
> +      <span>신고하기</span>
"신고하기" 텍스트도 피그마상에서는 폰트사이즈가 더 작은거로 알고있어요!
모바일에서 봤을때 특히 크게 보이는 것 같더라구요..! (글씨가 아래로 줄바꿈되는 현상이 일어남)

웹에서는 폰트사이즈가 10px이하로 안내려가는것으로 알 고 있는데 `zoom`속성을 이용하면 10px보다 더 작게 설정할 수 있습니다!
모바일에서 봤을때 글씨가 아래로 줄바꿈되지 않도록 반응형 처리를 해줘도 좋을 것 같아요! 👍

2023-07-13 16:34 UTC, JunJongHun commented
> 1. 모바일 크기일 때 게시글 제목은 지금처럼 둬도 괜찮지 않을까 싶어요..!
>    다만 오른쪽에 위치해 있는 신고하기와 스크랩 버튼이 모바일에서 너무 크게 보여서 영역을 침범하는 것 같습니다! 사이즈 적용해주면 괜찮을 것 같아요!
> 2. 낙관적 업데이트에 관한 피드백은 코드리뷰에 포함했습니다 🙂
> 3. 모달에 관련된 피드백도 코드리뷰에 포함했습니다 🙂
> 
> 로그인하지 않은 유저는 스크랩과 신고하기 버튼이 보이지 않게 구현하신 부분이 디테일하게 신경쓰신것 같아서 좋아요 🙌 한 가지 궁금한 점이 있는데, 현재 연동한 API에서 썸네일 사진이 404로 불러와지지 않더라구요! 해당 부분은 서버쪽에서 원래 404인 이미지를 넣어서 그런걸까요?

2023-07-14 07:06 UTC, JunJongHun commented on src/components/Trade/Report/ReportIcon/index.tsx
> +        }}
반영해서 수정했습니다! 모바일 사이즈에서는 크기를 더 작게하고 글씨를 안보이도록 했습니다. 확인 부탁드려요~😄

2023-07-14 07:10 UTC, JunJongHun commented on src/components/Trade/Report/ReportIcon/index.tsx
> +      />
아 저는 jQuery를 뭔가 사용하고 싶지 않아서 다른 방법이 있을까 고민을 해봤었습니다~😂

상민님이 css class를 만들어 두셨군요! 확인하고 수정했습니다👍

2023-07-14 07:12 UTC, JunJongHun commented on src/components/Trade/Report/ReportIcon/index.tsx
> +      <span>신고하기</span>
그래서 이 부분을 아예 안보이는 식으로 적용해봤어요! 저는 괜찮아 보이는데 혹시 글씨가 있는게 나은 것 같다면 `zoom` 속성을 이용해서 적용하겠습니다! 확인 부탁드립니다😄

2023-07-14 07:17 UTC, JunJongHun commented on src/components/Trade/Report/ReportModal/index.tsx
> +          </div>
해당 font-size를 적용을 안해었는데, 확인해보니 피그마 상에는 20px로 잡혀있네요~ 1.25로 적용 했습니다!

2023-07-14 07:32 UTC, JunJongHun commented on src/components/Trade/ScrapIcon/index.tsx
> +    },
좋아요 버튼을 누르는 로직에서는 좋아요 여부를 상태 값으로 따로 관리하고 있고, 게시글에 관한 api 응답값에는 좋아요 눌림 여부 판단 값이 없어서 그렇게 작성하셨을 것 같아요!

좋아요 수는 props로 전달받아서 사용하기 때문에 onSettled를 사용해서 좋아요 눌림 여부에 따라 좋아요 수가 바뀌다 보니 그렇게 작성하신 것 같아요! 맞겠죠..ㅎㅎ?

이거 외에도 작성하신 곳을 보면 중복되는 로직이 있어서 이 부분은 제가 리펙토링 진행해보도록 할게요~😄

2023-07-14 12:21 UTC, sangminlee98 commented on src/components/Trade/ScrapIcon/index.tsx
> +    },
좋아요! 감사합니다 :) 👍

2023-07-15 03:48 UTC, sangminlee98 commented on src/components/Trade/Report/ReportIcon/index.tsx
> +        }}
확인했습니다! 고생하셨어요 👍

2023-07-15 03:48 UTC, sangminlee98 approved these changes
확인했습니다! 고생하셨어요 :) 👍

2023-07-15 10:26 UTC, merged