Feat/#150 빈집거래 글쓰기 페이지 퍼블리싱
ODOICHON/frontend pull request #151
Opened 2023-07-16 09:40 UTC by JunJongHun

## 📖 개요
- 빈집거래 글쓰기 페이지 퍼블리싱

## 💻 작업사항

- 글쓰기 페이지 퍼블리싱
- 모바일 기준 '업로드', '주소 찾기' 버튼 아이콘으로 변경

## 💡 작성한 이슈 외에 작업한 사항

- X

## ？ 리뷰 받았으면 하는 부분
- css 부분이 깔끔하지 못한 것 같아서 한번 피드백 부탁드립니다. ( 중복되는 스타일을 어떻게 없애야 할지 감이 잘 안옵니다😭 )
- quill 부분에서 스크롤을 내리면 quill bar가 분리되는? 현상이 일어납니다. 이 부분은 왜그런걸까요..?

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2023-07-18 05:44 UTC, sangminlee98 requested changes
CSS 잘 짜신 것 같은데요?!
리뷰에 남긴 부분만 수정하면 될 것 같아요 👍

2023-07-18 05:44 UTC, sangminlee98 commented on src/components/Trade/Quill/styles.module.scss
> +  }
해당 부분은 CommunityQuill의 CSS를 가져오신 것 같아요!
커뮤니티 페이지의 경우 상단에 기본 Navbar에 커뮤니티의 Navbar가 덧붙혀 있기 때문에
`top: calc(77px + 70px)`인 이유가 기본 Navbar높이 77px + 커뮤니티 Navbar높이 70px를 더한 값으로 top을 지정해주었습니다.
빈집거래 경우에는 추가적인 Navbar가 없기 때문에 top: calc(77px); 으로만 적용하면 될 것 같아요!
mobile도 마찬가지입니다 🙂

2023-07-18 05:44 UTC, sangminlee98 commented on src/pages/Trade/Write/index.tsx
>      </motion.div>
해당 부분에서 p태그로 작성된 "지역과 관련된 내용을 작성해주세요." 부분은 피그마를 확인해 보니
font-weight와 color가 구현한 것과 다르더라구요!
수정부탁드립니다! 🙇‍♂️

2023-07-18 05:44 UTC, sangminlee98 commented on src/pages/Trade/Write/styles.module.scss
> +        }
이상하게 브라우저 너비가 딱 500px일때는 글씨랑 svg 둘 다 안보이더라구요..!
저희가 설정한 media가 문제인지.. 한번 확인 가능할까요?!

2023-07-19 11:32 UTC, JunJongHun commented on src/pages/Trade/Write/styles.module.scss
> +        }
저희가 작성한 media 코드입니다!
![code](https://github.com/ODOICHON/frontend/assets/90402926/5baa63c1-1ae4-45c3-9091-1c2ad4e63bb9)
이 코드를 실행해보니 500px 이하에서는 모바일, 500px 이상에서는 테블릿이 적용되게끔 작동하고, 작업한 코드에서 `span` `svg` 태그를 `display:none` 둘다 적용해서 딱 500px 때 안보이는 현상같습니다!

따라서, media.scss 코드를 변경했습니다.
![1](https://github.com/ODOICHON/frontend/assets/90402926/eb21b235-4049-42b1-994f-069ce4e4bc1c)
기준은 500px로 잡았지만 겹치는 현상이 있기 때문에, 500px - 1 이하에서는 모바일, 500px 이상에서는 테블릿으로 작동하게 하면 될 것 같습니다😄

2023-07-19 11:34 UTC, JunJongHun commented on src/components/Trade/Quill/styles.module.scss
> +  }
아~ 이해 했습니다! 감사합니다😄

2023-07-19 11:34 UTC, JunJongHun commented on src/pages/Trade/Write/index.tsx
>      </motion.div>
확인해보니 조금 다르네요.. 눈치를 못 챘습니다 하하😂 수정하겠습니다!

2023-07-19 12:07 UTC, JunJongHun commented
@sangminlee98 
상민님! 리뷰주신 부분 해결 했고, 빈집거래 글쓰기 페이지 피그마 디자인에 추가 UI가 생겨서 작업했습니다. 확인 부탁드려요!😄

2023-07-23 06:23 UTC, sangminlee98 commented on src/pages/Trade/Write/styles.module.scss
> +        }
앗.. 500px에서 걸렸던거군요 ㅋㅋㅋㅋ 확인 감사합니다!! 👍

2023-07-23 06:28 UTC, sangminlee98 approved these changes
확인했습니다 👍
글 쓰기 유형이 `매매/전세/월세`에 따라 필드값이 바뀌는 것도 나중에 연동하면서 작업하시면 될 것 같아요!
고생하셨습니다 🙇‍♂️

2023-07-24 18:55 UTC, merged