feat: 마이페이지 home 구현
ODOICHON/frontend pull request #174
Opened 2023-10-05 09:06 UTC by JunJongHun

## 💻 작업사항

- 마이페이지 필요한 api 연동
- 화면 퍼블리싱
- QueryKeys 추가

## 💡 궁금한점

- '이번주 인기 게시글' 부분에서 '더보러가기'를 누르면 인기 게시글 페이지로 가야한다. 
- /community/free_board 로 이동을 시키고 나서 '인기글'로 세팅을 하려면 추가적인 로직이 필요하다고 보인다. 어떻게 하는게 좋을까요?

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2023-10-05 13:30 UTC, sangminlee98 requested changes
요청한 부분 반영 부탁드립니다 🙇‍♂️

2023-10-05 13:30 UTC, sangminlee98 commented on src/pages/Mypage/home/index.tsx
> +  );
해당 부분의 API params에 현재 page만 들어가는데, 서버쪽에 요청해서 limit을 추가하여
원하는 갯수의 콘텐츠만 가져오도록 하면 더 좋을것 같아요!

2023-10-05 13:30 UTC, sangminlee98 commented on src/pages/Mypage/home/index.tsx
> +          </ul>
해당 부분은 피그마상에서 두개만 보여야 하는데 현재 코드에서는 불러온 데이터를 전부 보여주는 것 같아요!
수정이 필요할 것 같습니다!

2023-10-05 14:29 UTC, sangminlee98 commented on src/pages/Mypage/home/index.tsx
> +          </ul>
위에서 말한 것 처럼 서버에서 Limit을 추가한다면, 그 갯수만큼만 보여주도록 하면 될 것 같고
아니라면 slice해서 map을 하면 될 것 같아용

2023-10-07 00:56 UTC, JunJongHun commented on src/pages/Mypage/home/index.tsx
> +  );
네 좋아요👍 현재 서버쪽에서 limit는 params로 받지 않고 있어서 요청을 해야겠네요~ 다음주 회의 때, 얘기 하도록 하겠습니다!

2023-10-07 00:58 UTC, JunJongHun commented on src/pages/Mypage/home/index.tsx
> +          </ul>
`slice`를 깜빡 했네요! 확인해주셔서 감사합니다👍 우선, 적용하도록 하겠습니다!

추가적으로 서버에 요청해서 limit를 params로 넘길 수 있게 반영 된다면 추후에 반영하도록 하겠습니다😄

2023-10-07 01:24 UTC, JunJongHun commented
코드 리뷰 반영 했습니다!

인기순으로 선택되게 하는 과정에서 약간 고민을 했습니다.

- `state?.location ? 'POPULAR' : 'RECENT',`

- `state ? 'POPULAR' : 'RECENT',`

- `state?.location === '/mypage/home' ? 'POPULAR' : 'RECENT',`

우선 저는 첫번째를 택했습니다.
이유는 현재 로직에서는 location이 있거나 없거나 둘 중 하나기 때문에 state에 담긴 location 여부를 확인함으로써 코드상에서 어떤 경로에 대해서 무언가를 받을 수 있다는 것을 알리기 위함이였습니다. 제 의도대로 전달이 잘 되는지는 모르겠습니다😂

위 세가지 방법중에 어떤게 코드 가독성이 좋을지 의견 부탁드립니다! 또는 `useEffect`를 활용해서 조건 처리를 하는게 나을까요?

2023-10-12 11:49 UTC, sangminlee98 commented
> 코드 리뷰 반영 했습니다!
> 
> 인기순으로 선택되게 하는 과정에서 약간 고민을 했습니다.
> 
> * `state?.location ? 'POPULAR' : 'RECENT',`
> * `state ? 'POPULAR' : 'RECENT',`
> * `state?.location === '/mypage/home' ? 'POPULAR' : 'RECENT',`
> 
> 우선 저는 첫번째를 택했습니다. 이유는 현재 로직에서는 location이 있거나 없거나 둘 중 하나기 때문에 state에 담긴 location 여부를 확인함으로써 코드상에서 어떤 경로에 대해서 무언가를 받을 수 있다는 것을 알리기 위함이였습니다. 제 의도대로 전달이 잘 되는지는 모르겠습니다😂
> 
> 위 세가지 방법중에 어떤게 코드 가독성이 좋을지 의견 부탁드립니다! 또는 `useEffect`를 활용해서 조건 처리를 하는게 나을까요?

저는 세 번째 방법이 더 명시적이고 정확한 것 같아요..!
첫 번째랑 두 번째 방법은 코드를 봤을 때 의도를 잘 모르겠지만
세 번째 코드는 보면 의도가 명확히 보여서요..!

2023-10-12 11:50 UTC, sangminlee98 approved these changes
LGTM 👍

2023-10-19 03:09 UTC, merged