Feat/#194 내가 쓴 글 페이지 구현
ODOICHON/frontend pull request #195
Opened 2023-11-09 09:49 UTC by JunJongHun

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2023-11-13 10:31 UTC, sangminlee98 requested changes
`components/Community/Board/index.tsx` 컴포넌트에서 getCategoryName 함수에서 파라미터의 인자의 타입이 맞지 않다는 에러가 발생하고 있습니다.

제가 이전 PR에서 CategoryType 타입과 PrefixCategoryType 타입이 명시적이지 않아서 해당 타입을 삭제하고 string으로 대체했는데 종훈님께서 conflict 해결 과정에서 이전 코드로 다시 롤백하여 적용하신듯 합니다 😂

`src/types/Board/boardType.ts`에 있는 CategoryType와 PrefixCategoryType 타입은 삭제해주시고 해당 타입을 사용하는 곳에서는 전부 string 타입으로 대체 부탁드립니다!

2023-11-13 10:31 UTC, sangminlee98 commented on src/Routes.tsx
>  const IntroBoardPage = lazy(() => import('@/pages/Introduce/Board'));
모든 페이지를 code splitting을 하는게 오히려 사용자 경험이 더 안좋아지는 것 같아서
나중에 꼭 필요한 페이지에만 적용시키도록 고려해보면 좋을 것 같아요! 👍

2023-11-13 10:31 UTC, sangminlee98 commented on src/pages/Mypage/community/write/index.tsx
> +              prefixCategory={content.category || ''}
prefixCategory의 값을 왜 content.category로 넘겨주는지 알 수 있을까요??
제 예상대로면 content.prefixCategory로 넘겨줘야 할 것 같아서요..!

2023-11-13 10:31 UTC, sangminlee98 commented on src/pages/Mypage/community/write/index.tsx
> +              prefixCategory={content.category || ''}
CommunityBoard의 onClick 함수도 실행해보면
```tsx
      <li
        role="presentation"
        className={styles.wrapper}
        onClick={() => navigate(`/community/${prefixCategory}/${boardId}`)}
      >
```
이렇게 작성되어 있는데 실제로 이동되는 경로는 `http://localhost:3000/community//1` 로 이동이 됩니다..!
이 부분도 확인 부탁드려요!

2023-11-23 09:31 UTC, JunJongHun commented on src/pages/Mypage/community/write/index.tsx
> +              prefixCategory={content.category || ''}
prefixCategory를 넘겨주는게 맞습니다😂 알려주셔서 감사합니다!

2023-11-23 10:15 UTC, JunJongHun commented on src/Routes.tsx
>  const IntroBoardPage = lazy(() => import('@/pages/Introduce/Board'));
맞아요! 상민님이 말씀해주신대로 불필요한 lazy loading은 한번 같이 확인해보고 수정하면 좋을 것 같습니다😄

2023-11-23 10:17 UTC, JunJongHun commented on src/pages/Mypage/community/write/index.tsx
> +              prefixCategory={content.category || ''}
onclick 관련해서 해결법을 잘 못찾고 있었는데, 줌에서 알려주셔서 감사합니다👍

2023-11-23 13:04 UTC, sangminlee98 requested changes
게시글 이동 수정하신 로직 확인했습니다! 👍
다만 커뮤니티 게시글에 대해서 이동했을 때, 뒤로가기가 적용되지 않는 것 같아요!

### expected behavior
마이페이지 내가 쓴 글 페이지에서 커뮤니티 글 클릭 -> 커뮤니티 게시글 이동 -> 뒤로가기 -> 마이페이지 내가 쓴 글 페이지

### bug
마이페이지 내가 쓴 글 페이지에서 커뮤니티 글 클릭 -> 커뮤니티 게시글 이동 -> 뒤로가기 -> 동작하지 않음

아마도 이 부분 때문인 듯 합니다
```tsx
// pages/Community/Detail/index.tsx
  ...
  if (
    boardData &&
    category !== getPrefixCategoryName(boardData.data.prefixCategory)
  ) {
    const prefixCategory = getPrefixCategoryName(
      boardData?.data.prefixCategory,
    );
    return <Navigate to={`/community/${prefixCategory}/${id}`} />;
  }
  ...
```

다시 한 번 확인 부탁드립니다 🙇‍♂️

2023-11-28 06:28 UTC, JunJongHun commented
> 게시글 이동 수정하신 로직 확인했습니다! 👍 다만 커뮤니티 게시글에 대해서 이동했을 때, 뒤로가기가 적용되지 않는 것 같아요!
> 
> ### expected behavior
> 마이페이지 내가 쓴 글 페이지에서 커뮤니티 글 클릭 -> 커뮤니티 게시글 이동 -> 뒤로가기 -> 마이페이지 내가 쓴 글 페이지
> 
> ### bug
> 마이페이지 내가 쓴 글 페이지에서 커뮤니티 글 클릭 -> 커뮤니티 게시글 이동 -> 뒤로가기 -> 동작하지 않음
> 
> 아마도 이 부분 때문인 듯 합니다
> 
> ```tsx
> // pages/Community/Detail/index.tsx
>   ...
>   if (
>     boardData &&
>     category !== getPrefixCategoryName(boardData.data.prefixCategory)
>   ) {
>     const prefixCategory = getPrefixCategoryName(
>       boardData?.data.prefixCategory,
>     );
>     return <Navigate to={`/community/${prefixCategory}/${id}`} />;
>   }
>   ...
> ```
> 
> 다시 한 번 확인 부탁드립니다 🙇‍♂️

확인해주셔서 감사합니다!

수정해본 결과 마이페이지에서 넘겨주는 `prefixCategory`값이 `'DEFAULT'` 값이 여서 Community Detail page에 도착했을 때, 조건문에 걸렸습니다.
`'DEFAULT'` 값을 `'free_board'`로 바꾸는 과정에서 다시 한번 Community Detail page로 redirect를 해서 뒤로가기가 안되는 것이였습니다!

덕분에 쉽게 해결했습니다👍

2023-11-28 16:29 UTC, sangminlee98 approved these changes
동작 문제없이 잘 되는거 확인했습니다!
고생하셨습니다 🙇‍♂️

2023-11-28 16:29 UTC, sangminlee98 commented on src/components/Community/Board/index.tsx
> +        onClick={() => handleClick(prefixCategory, boardId)}
handleClick 함수를 추가하여 라우팅 주소를 계산하도록 하셨군요! 👍

2023-11-28 16:31 UTC, merged