게시글 작성 시 S3 이미지 관련 기능 추가
ODOICHON/frontend pull request #274
Opened 2024-06-09 20:32 UTC by sangminlee98

## 📖 개요
게시글 작성 중 페이지 이탈 시 업로드된 이미지를 S3에서 삭제합니다.
게시글 업로드 시 실제로 사용되는 이미지를 제외하고 에디터에서 지웠던 이미지에 대해 S3에서 삭제합니다.
기존에 적용했던 CloudFront 관련 코드를 제거합니다.

## 💻 작업사항

- 게시글 작성 시 업로드한 이미지의 URL을 저장하는 imageStore 전역 변수를 선언했습니다.
- 게시글 업로드 시 imageStore와 작성한 게시글의 이미지를 비교하여 삭제된 이미지들에 대해 S3에서 삭제하도록 했습니다.
- 게시글 작성 중 페이지를 이탈했을 때 게시글에 작성된 이미지들을 S3에서 삭제하도록 했습니다.

## 💡 작성한 이슈 외에 작업한 사항

- 기존에 적용했던 CloudFront 관련 코드를 제거합니다.

## ✔️ 공유 내용
- 이미 업로드된 게시글의 이미지는 사용자가 추후에 게시글 수정이나 게시글 삭제하여도 S3에서 삭제되지 않도록 하였습ㅁ니다.

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-06-13 13:36 UTC, JunJongHun requested changes
게시글 입력 중에 페이지 이탈시, 이미지 지웠을 때 모두 delete 되는 것을 네트워크 탭을 통해서 확인했습니다. 위에 변경 사항만 적용해주시고 merge 해주세요👍

수고하셨습니다~

2024-06-13 13:36 UTC, JunJongHun commented on src/components/Community/Quill/index.tsx
> +    const notUsedImageUrls = images.filter((url) => !imageUrls.includes(url));
이 코드가 반복되는거 같아서 함수로 빼면 좋을 것 같아요😄

2024-06-13 15:50 UTC, sangminlee98 commented on src/components/Community/Quill/index.tsx
> +    const notUsedImageUrls = images.filter((url) => !imageUrls.includes(url));
이 부분이 조금 고민됐습니다.
외부 함수로 빼자니 단순 filter하는 로직이 한줄이 전부라 오히려 불필요한 import가 생기지 않을까 고민했는데 어떻게 생각하시나요?? 🤔

2024-06-13 18:48 UTC, JunJongHun commented on src/components/Community/Quill/index.tsx
> +    const notUsedImageUrls = images.filter((url) => !imageUrls.includes(url));
상민님이 생각하시는 **불필요한 import**는 어떤 의미신가요?! 예를 들면 가독성 저하 등 있을 것 같네요😄

제 생각은 아래와 같습니다.

1. 혹여나 코드 로직이 변경되어야 하는 경우에 예상치 못한 버그를 방지할 수 있기에 좋은 방향이라고 생각했습니다! 하지만 로직상 변화가 있을 것 같지는 않아 보이긴 하네요🤔
2. 상민님이 말씀해주신 불필요한 import에 대한 제 생각은 성능 이슈는 없을 것 같고, 가독성 측면에서도 괜찮을 것 같습니다. 물론 가독성은 개인마다 차이가 있을 수 있겠네요😂

크게 문제가 되는 부분은 아닌 것 같아서 외부 함수로 빼는 것, 기존 코드 유지에 대해서는 문제 없어 보입니다😄

2024-06-14 04:06 UTC, sangminlee98 commented on src/components/Community/Quill/index.tsx
> +    const notUsedImageUrls = images.filter((url) => !imageUrls.includes(url));
제가 말씀드린 불필요한 import는 **한 파일에 너무 많은 import로 인한 가독성 저하**와  말씀해주신 **코드 가독성** 이었습니다!

여러 줄로 반복되는 코드라면 함수로 묶어 사용하는 것이 가독성이 더 좋을 수 있지만 이 경우에는 filter 메소드를 사용하여 기존 이미지 URL에서 사용되는 이미지만 걸러내는 작업을 수행하고 있기 때문에 함수를 사용하는 것 보다 더 구조적으로 어떻게 동작하는지 명시적으로 보여준다고 생각했어요!

하지만 종훈님께서 말씀해주신 것 처럼 추후에 코드 로직이 변경되야 하는 경우 번번히 사용하는 파일에서 수정하는 것은 바람직하지 않아 보이네요 😅
외부 함수로 따로 빼두어서 수정하겠습니다! 감사합니다 🙇‍♂️

2024-06-14 04:31 UTC, JunJongHun approved these changes

2024-06-14 04:31 UTC, merged